#@auth_token = 1a23fcd59c9fd475fab6ea37b898ae973b38c223cd0767c5e6f40a7fb86159b4
# user:
@auth_token = 5b80ba857d9913fb756afbd7b2aa2ec0d56b699830e77ba53855679cb1d252da


### Сохранение рецепта
POST localhost:8080/
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "Pasta",
  "ingredients": [
    { "amount": 200, "type": "grams of pasta22" },
    { "amount": 50, "type": "grams of cheese33" }
  ],
  "temperature": 100
}

> {% client.global.set("recipe_id", JSON.parse(response.body).id ); %}


### Получение рецепта
GET localhost:8080/?id={{recipe_id}}
Content-Type: application/json
Authorization: {{auth_token}}

### Получение рецепта без авторизации
GET localhost:8080/?id={{recipe_id}}
Content-Type: application/json

### Удаление рецепта
DELETE localhost:8080/?id={{recipe_id}}
Content-Type: application/json
Authorization: {{auth_token}}